# Generated by Django 5.2.3 on 2025-10-21 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_profile_app_version_profile_average_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='full_name',
        ),
    ]
