# Generated by Django 5.2.3 on 2025-10-23 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_profile_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='preferred_payment_method',
            field=models.CharField(blank=True, choices=[('bank_transfer', 'Bank Transfer'), ('telebirr', 'Tele Birr'), ('cash', 'Cash'), ('system_coin', 'System Coin'), ('others', 'Others')], max_length=255),
        ),
    ]
