# Generated by Django 5.2.3 on 2025-11-10 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_profile_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='contact_info',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='country_of_residence',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='preferences',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='travel_history',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_identity_verified',
            field=models.CharField(choices=[('idle', 'Idle'), ('pending', 'Pending'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='idle', max_length=10),
        ),
    ]
