# Generated by Django 5.2.3 on 2025-11-17 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_profile_contact_info_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelPriceSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_document', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_phone', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_per_tablet', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_per_pc', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_per_file', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_full_suitcase', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='price_setting', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
