# Generated by Django 5.2.3 on 2026-01-12 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_travelpricesetting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelpricesetting',
            name='price_per_file',
        ),
    ]
