# Generated by Django 5.2.3 on 2025-12-23 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0002_wallet_locked_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True)),
                ('swift', models.CharField(blank=True, max_length=50, null=True)),
                ('acct_length', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_mobilemoney', models.BooleanField(default=False)),
                ('currency', models.CharField(default='ETB', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banks', to='money.paymentgateway')),
            ],
            options={
                'unique_together': {('gateway', 'code')},
            },
        ),
    ]
