# Generated by Django 5.2.3 on 2026-01-16 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_remove_travellisting_price_per_file_and_more'),
        ('money', '0003_bank'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_balance_for_travel_listing', models.DecimalField(decimal_places=2, default=10.0, help_text='Minimum wallet balance required to create a travel listing', max_digits=10)),
                ('min_balance_for_package_request', models.DecimalField(decimal_places=2, default=10.0, help_text='Minimum wallet balance required to create a package request', max_digits=10)),
                ('platform_commission_percentage', models.DecimalField(decimal_places=2, default=5.0, help_text='Percentage commission taken from completed package deliveries', max_digits=5)),
                ('tax_percentage', models.DecimalField(decimal_places=2, default=15.0, help_text='Tax/VAT percentage', max_digits=5)),
                ('min_deposit_amount', models.DecimalField(decimal_places=2, default=10.0, help_text='Minimum amount for deposits', max_digits=10)),
                ('max_deposit_amount', models.DecimalField(decimal_places=2, default=10000.0, help_text='Maximum amount for deposits', max_digits=10)),
                ('min_withdrawal_amount', models.DecimalField(decimal_places=2, default=50.0, help_text='Minimum amount for withdrawals', max_digits=10)),
                ('max_withdrawal_amount', models.DecimalField(decimal_places=2, default=5000.0, help_text='Maximum amount for withdrawals', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Platform Configuration',
                'verbose_name_plural': 'Platform Configuration',
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='recipient_wallet',
            field=models.ForeignKey(blank=True, help_text='Recipient wallet for transfers', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_transactions', to='money.wallet'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='related_listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='listings.travellisting'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='related_package_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='listings.packagerequest'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_category',
            field=models.CharField(choices=[('USER_TRANSACTION', 'User Transaction'), ('SYSTEM_REVENUE', 'System Revenue'), ('INTERNAL_TRANSFER', 'Internal Transfer')], default='USER_TRANSACTION', help_text='Category for ledger tracking', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('LISTING_FEE', 'Travel Listing Fee'), ('REQUEST_FEE', 'Package Request Fee'), ('PAYMENT_LOCK', 'Payment Lock'), ('PAYMENT_UNLOCK', 'Payment Unlock'), ('PAYMENT_RELEASE', 'Payment Release'), ('COMMISSION', 'Platform Commission')], max_length=20),
        ),
    ]
