# Generated by Django 5.2.3 on 2025-12-29 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_alter_travellisting_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travellisting',
            name='price_per_document',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='travellisting',
            name='price_per_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
