# Generated by Django 5.2.3 on 2026-01-12 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_alter_travellisting_price_per_document_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travellisting',
            name='price_per_file',
        ),
        migrations.AlterField(
            model_name='travellisting',
            name='currency',
            field=models.CharField(default='ETB', max_length=10),
        ),
    ]
