# Generated by Django 5.2.3 on 2026-01-04 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0005_alter_message_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='package_request',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='travel_listing',
        ),
    ]
