# Generated by Django 5.2.3 on 2026-01-21 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0007_notification_conversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageattachment',
            name='public_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
